### ISSUE TITLE
Hash checking doesn't work

### ISSUE THREAD

**Issue by Vojtak42** [Sak32009/GetDataFromSteam-SteamDB#172]
Hi,
from version 5.4.0 and above the "Get data from Steam/Steamdb vX.X.X" button doesn't appear on https://steamdb.info/depot/[appid]/?show_hashes page. V5.3.9 works fine. I'm using Tampermonkey and Firefox.
Thanks for fixing.
Have a nice day

**Comment by KaladinDMP** [comment]
This isn't a bug but a feature, the way it's used was changed to be able to hash more branches, choose public first or whatever branch you want to hash them add it and the button will appear. More info on the Rin thread

**Comment by Vojtak42** [comment]
Sorry then😅, i didn't look on the Rin thread
